version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: xet_living_table
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
      - "33060:33060"
    volumes:
      - mysql_data:/var/lib/mysql

networks:
  default:
    driver: bridge
volumes:
  mysql_data: