version: "3.9"
services:
  frontend:
    image: xet-frontend-img
    container_name: xet-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped     
    networks:
      - app-network 
    depends_on:
      - backend

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: xet_living_table
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
    volumes:
      - ./backend/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    
  backend:
    image: xet-backend-img
    container_name: xet-backend
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:8001"
    networks:
      - app-network
    depends_on:
      - mysql

  netdata:
    image: netdata/netdata
    container_name: netdata
    restart: unless-stopped
    ports:
      - "19999:19999"
    environment:
      - DO_NOT_TRACK=YES
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
