version: "3.9"
services:
  frontend:
    image: xet-frontend-img
    container_name: xet-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped     
    networks:
      - app-network 

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: xet_living_table
      MYSQL_USER: app
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
      - "33060:33060"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
