
name: dev-1-backend

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  push:
    branches: [ "dev-1-backend" ]
  pull_request:
    branches: [ "dev-1-backend" ]



jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          ref: dev-1-backend
      - name: 安装最新版git
        run: |
          sudo apt update
          sudo apt install git
          git -v

      - name: 安装最新版g++编译器
        run: |
          sudo apt install build-essential g++
          g++ -v

      - name: 安装最新版CMake
        run: |
          sudo apt install cmake
          cmake --version
          
      - name: 安装oatpp
        run: |
          git clone https://github.com/oatpp/oatpp.git
          git checkout 1.3.0-latest
          cd oatpp
          mkdir build && cd build
          cmake .. && make install
          cd ../..

      - name: 安装oatpp-websocket
        run: |
          git clone https://github.com/oatpp/oatpp-websocket.git
          git checkout 1.3.0-latest
          cd oatpp-websocket
          mkdir build && cd build
          cmake .. && make install
          cd ../..
      
      - name: 安装MySQL Connect/C++
        run: |
          curl -LO https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconnx2-dbgsym_9.3.0-1ubuntu24.04_amd64.deb
          curl -LO https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn10-dbgsym_9.3.0-1ubuntu24.04_amd64.deb
          curl -LO https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn-dev_9.3.0-1ubuntu24.04_amd64.deb
          curl -LO https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconnx2_9.3.0-1ubuntu24.04_amd64.deb
          curl -LO https://dev.mysql.com/get/Downloads/Connector-C++/libmysqlcppconn10_9.3.0-1ubuntu24.04_amd64.deb
          dpkg -i libmysqlcppconnx2-dbgsym_9.3.0-1ubuntu24.04_amd64.deb
          dpkg -i libmysqlcppconn10-dbgsym_9.3.0-1ubuntu24.04_amd64.deb
          dpkg -i libmysqlcppconn-dev_9.3.0-1ubuntu24.04_amd64.deb
          dpkg -i libmysqlcppconnx2_9.3.0-1ubuntu24.04_amd64.deb
          dpkg -i libmysqlcppconn10_9.3.0-1ubuntu24.04_amd64.deb
          echo install MySQL Connect/C++ complete!.

      - name: 构建并运行后端
        run: |
          cd xet-OnlineLivingStream/xet-backend/xet-backend-async
          mkdir build && cd build
          cmake .. && make
          ./xet-backend-async-exe &
          cd ../xet-backend-sync
          mkdir build && cd build
          cmake .. && make
          ./xet-backend-sync-exe &
          
          
      

