name: Deploy to 47.107.61.250

on:
  push:
    branches:
      - dev2
  pull_request:
    branches:
      - dev2
  workflow_dispatch:  # 👈 添加手动启动触发器

jobs:
  deploy:
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          # 这里SSH_PRIVATE_KEY是你的.pem私钥内容

      - name: Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no root@47.107.61.250 <<EOF
          cd /home/admin
          cd xet-OnlineLivingStream
          git switch dev2 
          cd ..
          /home/admin/xet-OnlineLivingStream/local-deploy.sh
          EOF
